trigger: none

pool:
  name: LinuxPool

variables:
  working-directory: 'virtualMachine'

stages:
  - stage: infra
    jobs:
      - job: terraformJob
        displayName: "Provision Infrastructure with Terraform"
        steps:
          - checkout: self
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(working-directory)'
              backendServiceArm: 'DjAzureSPNConnection'
              backendAzureRmStorageAccountName: 'dhanustorage03'
              backendAzureRmContainerName: 'dhanucontainer'
              backendAzureRmKey: 'vmstorage123.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(working-directory)'
              environmentServiceNameAzureRM: 'DjAzureSPNConnection'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(working-directory)'
              environmentServiceNameAzureRM: 'DjAzureSPNConnection'
              
          - script: |
              cd $(working-directory)
              mkdir -p /home/dhanu/shared/ansible
              terraform output -raw ansible_inventory > /home/dhanu/shared/ansible/inventory.ini
          
          - script: |
              cd $(working-directory)
              terraform output -raw vm_ip > $(Pipeline.Workspace)/vm_ip.txt
              echo "VM IP saved to $(Pipeline.Workspace)/vm_ip.txt"
            displayName: "Save VM IP to file"
          - publish: $(Pipeline.Workspace)/vm_ip.txt
            artifact: vm_ip
            displayName: "Publish VM IP"

  - stage: config
    dependsOn: infra
    jobs:
      - job: ansibleJob
        displayName: "Configure VMs with Ansible"
        steps:
          - checkout: self

          - script: |
              export ANSIBLE_HOST_KEY_CHECKING=False
              ansible-playbook -i /home/dhanu/shared/ansible/inventory.ini ansible/playbook.yml
            displayName: "Run Ansible Playbook"

  - stage: Docker
    dependsOn: config
    jobs:
      - job: BuildPush
        pool:
          name: LinuxPool
          steps:
            - task: Docker@2
              inputs:
                containerRegistry: 'docker0395'
                repository: 'dhanu0395/dockervm'
                command: 'buildAndPush'
                Dockerfile: '$(Build.SourcesDirectory)/docker/Dockerfile'
                buildContext: '$(Build.SourcesDirectory)'
                tags: |
                  latest   

  - stage: Deploy
    dependsOn: Docker
    jobs:
      - job: DeployApp
        pool:
          name: LinuxPool
        steps:
          - task: AzureKeyVault@2
            name: FetchSecrets
            inputs:
              azureSubscription: 'DjAzureSPNConnection'
              KeyVaultName: 'dhanu-keyvault'
              SecretsFilter: 'vmpassword,dockerPassword'
              RunAsPreJob: true
          - script: |
              VM_IP=$(cat $(Pipeline.Workspace)/vm_ip.txt)
              echo "Using VM IP: $VM_IP"

              sshpass -p "$(vmpassword)" ssh -o StrictHostKeyChecking=no azureuser@$VM_IP "
                docker login -u dhanu0395 -p $(dockerPassword)
                docker pull dhanu0395/dockervm:latest
                docker run -d -p 80:80 dhanu0395/dockervm:latest"
            displayName: Run Docker Container          

